# docker-compose file for launching a testing version of your prisma service
# requires Docker Desktop https://www.docker.com/products/docker-desktop
# requires that you have pulled the corresponding prisma and postgres-db images from docker hub
# see README section on `Testing` for more information
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres-db
            port: 5432
            user: prisma
            password: prisma
  postgres-db:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~